/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  account_email: string;
  account_id: string;
  account_name: string;
  account_password: string;
  account_role: string;
  account_status: string;
  created_at: number | null;
  updated_at: number | null;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migration_time: Date | null;
  name: string | null;
}

export interface DB {
  account: Account;
  knex_migrations: KnexMigrations;
}
